spring:
  application:
    name: smart-mobility-gateway-01
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.20.1.242:8080/realms/smart-mobility
  #          issuer-uri: http://localhost:8080/realms/smart-mobility
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-mobility-pass-service
          predicates:
            - Path=/users/**
        - id: trip-service
          uri: lb://trip-management-service
          predicates:
            - Path=/trips/**
        - id: pricing-service
          uri: lb://smart-mobility-pricing-service
          predicates:
            - Path=/api/pricing/**
        - id: billing-service
          uri: lb://smart-mobility-billing-service
          predicates:
            - Path=/accounts/**
        - id: catalog-service
          uri: lb://smart-mobility-user-service
          predicates:
            - Path=/api/catalog/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG

server:
  port: 8765
  address: 0.0.0.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    ip-address: 192.168.16.104
management:
  tracing:
    export:
      zipkin:
        endpoint: http://localhost:9411/api/v2/spans